# version 3.9
#version: '3.9'

services:

  

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - go_network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - go_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - go_network

  auth-service:
    build:
      context: .
      dockerfile: ./micro-services/auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: auth-service
      SERVICE_PORT: 8081
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=auth
      KAFKA_BROKERS: kafka:9092
      GRPC_PORT: 50051
    ports:
      - "8081:8081"
      - "50051:50051"
    networks:
      - go_network

  transaction-service:
    build:
      context: .
      dockerfile: ./micro-services/transaction-service/Dockerfile
    container_name: transaction-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: transaction-service
      SERVICE_PORT: 8082
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=transaction
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8082:8082"
    networks:
      - go_network

  wallet-service:
    build:
      context: .
      dockerfile: ./micro-services/wallet-service/Dockerfile
    container_name: wallet-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: wallet-service
      SERVICE_PORT: 8083
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=wallet
      KAFKA_BROKERS: kafka:9092
      GRPC_PORT: 50052
    ports:
      - "8083:8083"
    networks:
      - go_network

  settlement-service:
    build:
      context: .
      dockerfile: ./micro-services/settlement-service/Dockerfile
    container_name: settlement-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: settlement-service
      SERVICE_PORT: 8084
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=settlement
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8084:8084"
    networks:
      - go_network

  business-service:
    build:
      context: .
      dockerfile: ./micro-services/business-service/Dockerfile
    container_name: business-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: business-service
      SERVICE_PORT: 8085
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=business
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8085:8085"
    networks:
      - go_network

  notification-service:
    build:
      context: .
      dockerfile: ./micro-services/notification-service/Dockerfile
    container_name: notification-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: notification-service
      SERVICE_PORT: 8086
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=notification
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8086:8086"
    networks:
      - go_network

  report-service:
    build:
      context: .
      dockerfile: ./micro-services/report-service/Dockerfile
    container_name: report-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: report-service
      SERVICE_PORT: 8087
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=report
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8087:8087"
    networks:
      - go_network

  compliance-service:
    build:
      context: .
      dockerfile: ./micro-services/compliance-service/Dockerfile
    container_name: compliance-service
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
    environment:
      SERVICE_NAME: compliance-service
      SERVICE_PORT: 8088
      DATABASE_URL: postgres://admin:admin@postgres:5432/main?sslmode=disable&schema=compliance
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8088:8088"
    networks:
      - go_network

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    depends_on:
      - auth-service
      - business-service
      - transaction-service
      - compliance-service
      - report-service
    environment:
      SERVICE_NAME: api-gateway
      SERVICE_PORT: 8080
      AUTH_GRPC: auth-service:50051
      WALLET_GRPC: business-service:50052
      TRANSACTION_GRPC: transaction-service:50053
    ports:
      - "8080:8080"
    networks:
      - go_network


volumes:
  postgres_data:

networks:
  go_network:
    driver: bridge
